baseURL: https://amqfundicion.netlify.app/
languageCode: en-us
title: AMQ FUNDICION
themesDir: themes
theme: hugo-hero-theme
module:
  hugoVersion:
    extended: yes
    min: 0.92.0


params:
  homepage_meta_tags:
    meta_description: a description of your website.
    meta_og_title: My Theme
    meta_og_type: website
    meta_og_url: 'https://www.mywebsite.com'
    meta_og_image: 'https://www.mywebsite.com/images/tn.png'
    meta_og_description: a description of your website.
    meta_twitter_card: summary
    meta_twitter_site: '@mytwitterhandle'
    meta_twitter_creator: '@mytwitterhandle'
params:
  homepage_meta_tags:
    meta_description: a description of your website.
    meta_og_title: My Theme
    meta_og_type: website
    meta_og_url: 'https://www.mywebsite.com'
    meta_og_image: 'https://www.mywebsite.com/images/tn.png'
    meta_og_description: a description of your website.
    meta_twitter_card: summary
    meta_twitter_site: '@mytwitterhandle'
    meta_twitter_creator: '@mytwitterhandle'


 
  
  logo:
    alt: AMQ 
    desktop: LOGO AMQ.ico
    desktop_height: 29px
    desktop_width: 217px
    mobile: images/logo-mobile.svg
    mobile_height: 36px
    mobile_width: 36px
    
menu:
  main:
    - name: Misi贸n 
      url: /Misi贸n/
      weight: 1
    - name: Visi贸n
      url: /Visi贸n/
      weight: 2
    - name: Valores
      url: /Valores /
      weight: 3
    - name: Aleaciones
      url: /Aleaciones /
      weight: 3
    - name: Contacto
      url: /Contacto/
      weight: 4
permalinks:
  pages: /:filename/
  post: /:year/:month/:day/:slug/
