baseURL: https://amqfundicion.netlify.app/
languageCode: en-us
title: AMQ FUNDICION
theme: hugo-hero-theme
module:
  hugoVersion:
    extended: yes
    min: 0.92.0

params:
    google_analytics_id: ""
    logo:
          alt: AMQ 
          desktop: LOGO AMQ.ico
    desktop_height: 29px
    desktop_width: 217px
    mobile: q.png
    mobile_height: 36px
    mobile_width: 36px

menu:
  main:
    - name: Misión y Visión
      url: /mision/
      weight: 1
    - name: Valores
      url: /post/
      weight: 3
    - name: Aleaciones 
      url: /services/
      weight: 4
    - name: Contacto
      url: /contacto/
      weight: 5
permalinks:
  pages: /:filename/
  post: /:year/:month/:day/:slug/
