baseURL: https://amqfundicion.netlify.app/
languageCode: en-us
title: AMQ FUNDICION
theme: hugo-hero-theme
module:
  hugoVersion:
    extended: yes
    min: 0.92.0

params:
    google_analytics_id: ""
    logo:
          alt: AMQ 
          desktop: LOGO AMQ.ico
    desktop_height: 29px
    desktop_width: 217px
    mobile: images/LOGO AMQ.ico
    mobile_height: 75px
    mobile_width: 167px
assets: 
 favicon: "favicon_io/favicon.ico" 
 favicon16x16:  "favicon_io/16.png" 
 favicon32x32:  "favicon_io/32.png" 
 apple_touch_icon:  "favicon_io/apple.png" 
   
menu:
  main:
    - name: Misión y Visión
      url: /mision/
      weight: 1
    - name: Valores
      url: /post/
      weight: 2
    - name: Política de calidad 
      url: /pc/
      weight: 3
    - name: Aleaciones 
      url: /services/
      weight: 4
    - name: Contacto
      url: /contacto/
      weight: 5
permalinks:
  pages: /:filename/
  post: /:year/:month/:day/:slug/
