baseURL: https://amqfundicion.netlify.app/
languageCode: en-us
title: AMQ FUNDICION
theme: hugo-hero-theme
module:
  hugoVersion:
    extended: yes
    min: 0.92.0

params:
    google_analytics_id: ""
    logo:
          alt: AMQ 
          desktop: LOGO AMQ.ico
    desktop_height: 29px
    desktop_width: 217px
    mobile: images/logo-mobile.svg
    mobile_height: 36px
    mobile_width: 36px

menu:
  main:
    - name: Misi贸n 
      url: /Misi贸n/
      weight: 1
    - name: Visi贸n
      url: /Visi贸n/
      weight: 2
    - name: Valores
      url: /Valores /
      weight: 3
    - name: Aleaciones
      url: /Aleaciones /
      weight: 3
    - name: Contacto
      url: /contacto/
      weight: 4
permalinks:
  pages: /:filename/
  post: /:year/:month/:day/:slug/
